server:
  port: 8080

spring:
  application:
    name: crew-control-api
  datasource:
    url: jdbc:postgresql://localhost:5432/crew_control_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}

# swagger-ui custom path
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
